#!/usr/bin/env python3
"""Generate the auto-town-rights eligibility triggers from vanilla data.

Reads every vanilla `town_rights_type` definition and emits two scripted triggers,
each a single branch chain keyed by town right:

  cm_can_grant_specific_town_right_at_location - the right's `allow` block, the
      per-location restriction the engine applies when granting.
  cm_auto_town_rights_potential_passes - the advance whose `unlock_town_rights`
      names the right, plus the right's `potential` block, the country-level
      prerequisites. Rights unlocked by an advance are read out of
      in_game/common/advances/.

Both bodies are copied without rewriting: the callers save the candidate location
as scope:target and the right as scope:cm_town_right, which are exactly the scopes
vanilla `allow` and `potential` blocks read. New triggers Paradox adds pass straight
through on the next regeneration.

Usage:
    python tools/cm_generate_town_rights_allow.py [--game-dir PATH]

The game directory comes from `game_directory` in tools/config.toml, or is
auto-detected from the common Steam install paths when that is blank.
"""

import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
CONFIG_PATH = os.path.join(SCRIPT_DIR, "config.toml")

STEAM_GAME_PATHS = [
    os.path.join("C:" + os.sep, "Steam", "steamapps", "common",
                 "Europa Universalis V", "game"),
    os.path.join("C:" + os.sep, "Program Files (x86)", "Steam", "steamapps",
                 "common", "Europa Universalis V", "game"),
    os.path.join("C:" + os.sep, "Program Files", "Steam", "steamapps",
                 "common", "Europa Universalis V", "game"),
]

TOWN_RIGHTS_SUBDIR = os.path.join("in_game", "common", "town_rights")
ADVANCES_SUBDIR = os.path.join("in_game", "common", "advances")

TRIGGERS_DIR = os.path.join(ROOT_DIR, "in_game", "common", "scripted_triggers")

ALLOW_OUTPUT_PATH = os.path.join(
    TRIGGERS_DIR, "cm_auto_town_rights_allow_triggers.txt")
POTENTIAL_OUTPUT_PATH = os.path.join(
    TRIGGERS_DIR, "cm_auto_town_rights_potential_triggers.txt")

ALLOW_TRIGGER_NAME = "cm_can_grant_specific_town_right_at_location"
POTENTIAL_TRIGGER_NAME = "cm_auto_town_rights_potential_passes"

ASSIGN_BLOCK = re.compile(r"([A-Za-z_][A-Za-z0-9_.:]*)\s*=\s*\{")
ASSIGN_SCALAR = re.compile(
    r"^\s*([A-Za-z_][A-Za-z0-9_.:]*)\s*=\s*([^\s{}]+)\s*$", re.MULTILINE)

GENERATED_BY = (
    "# Generated by tools/cm_generate_town_rights_allow.py - do not edit by hand.\n"
    "# Regenerate after a game update.\n"
    "#\n"
)

ALLOW_HEADER = (
    GENERATED_BY +
    "# Country trigger. Mirrors each vanilla town_rights_type `allow` block so auto-grant\n"
    "# only grants a right on a location the engine would allow it on.\n"
    "# Expects scope:cm_town_right (the right) and scope:target (the candidate location).\n"
    "# Rights with no `allow` restriction fall through to the trailing trigger_else.\n"
)

POTENTIAL_HEADER = (
    GENERATED_BY +
    "# Country trigger. Returns yes when the country currently meets the per-right\n"
    "# prerequisites for the town right in scope:cm_town_right: the unlocking advance\n"
    "# if any, plus the right's `potential` block if any.\n"
    "# The basic city_building_advance gate is checked separately at the call site\n"
    "# via modifier:can_grant_town_rights = yes.\n"
    "# Rights with neither an advance nor a `potential` fall through to the trailing\n"
    "# trigger_else.\n"
)


def _load_config():
    if tomllib is None:
        return {}
    try:
        with open(CONFIG_PATH, "rb") as f:
            return tomllib.load(f)
    except FileNotFoundError:
        return {}


def resolve_game_dir(cli_game_dir):
    if cli_game_dir:
        if os.path.isdir(cli_game_dir):
            return cli_game_dir
        sys.exit(f"Game directory not found: {cli_game_dir}")

    configured = _load_config().get("game_directory", "")
    if configured and os.path.isdir(configured):
        return configured

    for path in STEAM_GAME_PATHS:
        if os.path.isdir(path):
            return path

    sys.exit("Could not locate EU5 game directory. "
             "Set 'game_directory' in tools/config.toml or pass --game-dir.")


def strip_comments(text):
    """Drop `#` comments while preserving line structure for brace matching."""
    return "\n".join(line.split("#", 1)[0] for line in text.split("\n"))


def find_matching_brace(text, open_idx):
    depth = 0
    in_str = False
    for i in range(open_idx, len(text)):
        ch = text[i]
        if in_str:
            if ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError(f"unbalanced braces from offset {open_idx}")


def child_blocks(text):
    """Yield (name, inner_text) for each `name = { ... }` directly inside `text`."""
    pos = 0
    while True:
        match = ASSIGN_BLOCK.search(text, pos)
        if not match:
            return
        open_idx = match.end() - 1
        close_idx = find_matching_brace(text, open_idx)
        yield match.group(1), text[open_idx + 1:close_idx]
        pos = close_idx + 1


def remove_child_blocks(text):
    """Return `text` with every `name = { ... }` block blanked out."""
    out = []
    pos = 0
    while True:
        match = ASSIGN_BLOCK.search(text, pos)
        if not match:
            out.append(text[pos:])
            return "".join(out)
        close_idx = find_matching_brace(text, match.end() - 1)
        out.append(text[pos:match.start()])
        pos = close_idx + 1


def scalar_assignments(text):
    """Yield (key, value) for simple `key = value` lines outside child blocks."""
    for match in ASSIGN_SCALAR.finditer(remove_child_blocks(text)):
        yield match.group(1), match.group(2)


def reindent(body, base="\t\t"):
    lines = body.split("\n")
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    if not lines:
        return ""
    common = min(len(ln) - len(ln.lstrip("\t ")) for ln in lines if ln.strip())
    return "\n".join((base + ln[common:]).rstrip() if ln.strip() else ""
                     for ln in lines)


def iter_db_files(directory):
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".txt") or name in ("readme.txt", "__readme.txt"):
            continue
        yield os.path.join(directory, name)


def read_pdx(path):
    with open(path, "r", encoding="utf-8-sig") as f:
        return strip_comments(f.read())


def collect_right_blocks(town_rights_dir):
    """Return ordered (right, allow_body, potential_body) for every town right.
    Either body is "" when the right has no such block or an empty one."""
    rights = []
    for path in iter_db_files(town_rights_dir):
        for right_name, body in child_blocks(read_pdx(path)):
            blocks = dict(child_blocks(body))
            rights.append((right_name,
                           reindent(blocks.get("allow", "")),
                           reindent(blocks.get("potential", ""))))
    return rights


def parse_unlock_advances(advances_dir):
    """Return {town right: advance} for every `unlock_town_rights` in advances."""
    unlocks = {}
    for path in iter_db_files(advances_dir):
        for advance, body in child_blocks(read_pdx(path)):
            for key, value in scalar_assignments(body):
                if key == "unlock_town_rights":
                    unlocks[value] = advance
    return unlocks


def allow_branches(rights):
    return [(name, allow) for name, allow, _ in rights if allow]


def potential_branches(rights, unlock_advances):
    branches = []
    for name, _, potential in rights:
        parts = []
        advance = unlock_advances.get(name)
        if advance:
            parts.append(f"\t\thas_advance = {advance}")
        if potential:
            parts.append(potential)
        if parts:
            branches.append((name, "\n".join(parts)))
    return branches


def render(header, trigger_name, branches):
    body = []
    for idx, (name, block) in enumerate(branches):
        keyword = "trigger_if" if idx == 0 else "trigger_else_if"
        body.append(
            f"\t{keyword} = {{\n"
            f"\t\tlimit = {{ scope:cm_town_right = town_rights_type:{name} }}\n"
            f"{block}\n"
            f"\t}}"
        )
    body.append("\ttrigger_else = {\n\t\talways = yes\n\t}")
    return f"{header}{trigger_name} = {{\n" + "\n".join(body) + "\n}\n"


def write_output(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    data = b"\xef\xbb\xbf" + normalized.encode("utf-8")
    with open(path, "wb") as f:
        f.write(data)


def report(path, label, branches):
    rel = os.path.relpath(path, ROOT_DIR).replace(os.sep, "/")
    print(f"Wrote {len(branches)} {label} branches to {rel}")
    for name, _ in branches:
        print(f"  {name}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate the auto-town-rights eligibility triggers from "
                    "vanilla town_rights allow and potential blocks.")
    parser.add_argument(
        "--game-dir", type=str, default=None,
        help="Path to EU5 game directory (overrides config.toml).")
    args = parser.parse_args()

    game_dir = resolve_game_dir(args.game_dir)
    town_rights_dir = os.path.join(game_dir, TOWN_RIGHTS_SUBDIR)
    if not os.path.isdir(town_rights_dir):
        sys.exit(f"town_rights directory not found: {town_rights_dir}")
    advances_dir = os.path.join(game_dir, ADVANCES_SUBDIR)
    if not os.path.isdir(advances_dir):
        sys.exit(f"advances directory not found: {advances_dir}")

    rights = collect_right_blocks(town_rights_dir)
    if not rights:
        sys.exit(f"No town rights found in {town_rights_dir}")
    unlock_advances = parse_unlock_advances(advances_dir)

    allow = allow_branches(rights)
    if not allow:
        sys.exit(f"No town rights with allow blocks found in {town_rights_dir}")
    write_output(ALLOW_OUTPUT_PATH,
                 render(ALLOW_HEADER, ALLOW_TRIGGER_NAME, allow))
    report(ALLOW_OUTPUT_PATH, "allow", allow)

    potential = potential_branches(rights, unlock_advances)
    if not potential:
        sys.exit(f"No town rights with prerequisites found in {town_rights_dir}")
    write_output(POTENTIAL_OUTPUT_PATH,
                 render(POTENTIAL_HEADER, POTENTIAL_TRIGGER_NAME, potential))
    report(POTENTIAL_OUTPUT_PATH, "prerequisite", potential)


if __name__ == "__main__":
    main()
