#!/usr/bin/env python3
"""Generate the R.G.O. Bonus building filter script values from vanilla data.

Emits per-building-type script values scoring how much of a building's consumed
goods the surrounding province supplies as raw materials, the coverage the
Local Access to Raw Materials modifier (raw_material_in_province_impact)
scales. The filter itself and the modifier read are hand-authored:
cm_building_rgo_bonus in in_game/common/script_values/cm_filter_script_values.txt
multiplies the generated cm_rgob_coverage by the modifier value.

Reads vanilla building_types (production method slots: inline
unique_production_methods plus possible_production_methods references resolved
against common/production_methods) and goods (raw_material category). Emits:

  in_game/common/script_values/cm_rgo_bonus_filter_script_values.txt
  in_game/common/scripted_effects/cm_rgo_bonus_filter_effects.txt

The script values carry two dispatches over the same per-building coverage
values: cm_rgob_coverage (building scope, for the building-list filter) and
cm_rgob_coverage_selected (location scope, for the build-location filter),
which branches on the viewer's cm_rgob_selected_idx variable. The effects file
seeds the building_type -> index map (cm_rgob_type_index) that
cm_rgob_store_selected_type resolves that variable from.

Scoring model (same worth-using convention as the Best Urban Right map mode):
  - A building's main production slot is its slot with the highest output;
    other slots are enhancement slots and are ignored.
  - Worth-using production methods are those in the main slot with output at
    least PM_OUTPUT_THRESHOLD of the slot's best output.
  - A production method's coverage in a province is the sum of its input-amount
    shares whose good is a raw material somewhere in the province; goods that
    can never be raw materials still count in the denominator.
  - A building's coverage is the best coverage among its worth-using production
    methods (deduped and domination-pruned within the building).
  - allow/potential gates on production methods are ignored.

Usage:
    python tools/cm_generate_rgo_bonus_filter.py [--game-dir PATH]

The game directory comes from `game_directory` in tools/config.toml, or is
auto-detected from the common Steam install paths when that is blank.
"""

import argparse
import os

from cm_generate_town_rights_map_mode import (
    BUILDING_TYPES_SUBDIR,
    GOODS_SUBDIR,
    PM_OUTPUT_THRESHOLD,
    PRODUCTION_METHODS_SUBDIR,
    ROOT_DIR,
    child_blocks,
    dominates,
    fmt_amount,
    fmt_num,
    iter_db_files,
    parse_goods,
    parse_pm_body,
    parse_production_methods,
    province_check,
    read_pdx,
    resolve_game_dir,
    write_output,
)

OUT_SCRIPT_VALUES = os.path.join(
    ROOT_DIR, "in_game", "common", "script_values",
    "cm_rgo_bonus_filter_script_values.txt")
OUT_EFFECTS = os.path.join(
    ROOT_DIR, "in_game", "common", "scripted_effects",
    "cm_rgo_bonus_filter_effects.txt")

GENERATED_HEADER = (
    "# Generated by tools/cm_generate_rgo_bonus_filter.py - do not edit by hand.\n"
    "# Regenerate after a game update.\n"
)


def parse_buildings(game_dir, goods_categories, external_pms):
    """Return ({building: {ref, slots}}, dangling) where each slot is a list
    of PM dicts {name, ref, inputs, produced, output} and dangling is the set
    of possible_production_methods names with no external definition."""
    buildings = {}
    dangling = set()
    directory = os.path.join(game_dir, BUILDING_TYPES_SUBDIR)
    for name, path in iter_db_files(directory):
        rel = os.path.join(BUILDING_TYPES_SUBDIR, name).replace(os.sep, "/")
        text = read_pdx(path)
        for building, body, b_line in child_blocks(text):
            slots = []
            for child, inner, c_line in child_blocks(body):
                if child == "unique_production_methods":
                    slot = []
                    for pm, pm_body, pm_line in child_blocks(inner):
                        data = parse_pm_body(pm_body, goods_categories)
                        data["name"] = pm
                        data["ref"] = f"{rel}:{b_line + c_line + pm_line - 2}"
                        slot.append(data)
                    if slot:
                        slots.append(slot)
                elif child == "possible_production_methods":
                    slot = []
                    for pm in inner.split():
                        if pm not in external_pms:
                            dangling.add(pm)
                            continue
                        data = dict(external_pms[pm])
                        data["name"] = pm
                        slot.append(data)
                    if slot:
                        slots.append(slot)
            if slots:
                buildings[building] = {"ref": f"{rel}:{b_line}", "slots": slots}
    return buildings, dangling


def collect_building_options(buildings, goods_categories):
    """Return {building: {ref, options}}, option = {shares {good: share_str},
    comment}, for buildings with at least one worth-using production method
    consuming a raw material."""
    result = {}
    for building, data in sorted(buildings.items()):
        main_slot = max(
            data["slots"],
            key=lambda slot: max((pm["output"] or 0.0) for pm in slot))
        best_output = max((pm["output"] or 0.0) for pm in main_slot)
        if best_output <= 0:
            continue
        options = []
        seen = set()
        for pm in main_slot:
            if pm["output"] is None or not pm["inputs"]:
                continue
            if pm["output"] < PM_OUTPUT_THRESHOLD * best_output:
                continue
            total = sum(pm["inputs"].values())
            if total <= 0:
                continue
            shares = {}
            for input_good, amount in sorted(pm["inputs"].items()):
                if goods_categories.get(input_good) != "raw_material":
                    continue
                shares[input_good] = fmt_num(amount / total)
            if not shares:
                continue
            key = tuple(sorted(shares.items()))
            if key in seen:
                continue
            seen.add(key)
            mix = ", ".join(f"{g} {fmt_amount(a)}"
                            for g, a in sorted(pm["inputs"].items()))
            options.append({
                "shares": shares,
                "comment": (f"{pm['name']} ({building}), {pm['ref']} - "
                            f"{mix} of {fmt_amount(total)} total input"),
            })
        options = [o for o in options
                   if not any(dominates(a, o) for a in options if a is not o)]
        if options:
            result[building] = {"ref": data["ref"], "options": options}
    return result


def emit_option_body(lines, option, indent="\t"):
    lines.append(f"{indent}value = 0")
    for input_good, share in option["shares"].items():
        lines.append(f"{indent}if = {{")
        lines.append(f"{indent}\tlimit = {{ {province_check(input_good)} }}")
        lines.append(f"{indent}\tadd = {share}")
        lines.append(f"{indent}}}")


def emit_script_values(options_by_building):
    lines = [GENERATED_HEADER]
    lines.append(
        "# Province-scoped values for the R.G.O. Bonus building filter: per building,\n"
        "# each option is one worth-using main-slot production method's input share\n"
        "# available as province raw materials, cm_rgob_b_<building> is the best option,\n"
        "# and cm_rgob_coverage (building scope) dispatches on the building type.\n"
        "# Consumed by cm_building_rgo_bonus in cm_filter_script_values.txt.\n")

    for building, data in options_by_building.items():
        options = data["options"]
        if len(options) == 1:
            lines.append(f"# {building}: {data['ref']}")
            lines.append(f"# {options[0]['comment']}")
            lines.append(f"cm_rgob_b_{building} = {{")
            emit_option_body(lines, options[0])
            lines.append("}")
        else:
            for k, option in enumerate(options, start=1):
                lines.append(f"# {option['comment']}")
                lines.append(f"cm_rgob_o_{building}_{k} = {{")
                emit_option_body(lines, option)
                lines.append("}")
            lines.append(f"# {building}: {data['ref']}")
            lines.append(f"cm_rgob_b_{building} = {{")
            lines.append(f"\tvalue = cm_rgob_o_{building}_1")
            for k in range(2, len(options) + 1):
                lines.append(f"\tmin = cm_rgob_o_{building}_{k}")
            lines.append("}")
        lines.append("")

    lines.append("# Building scope.")
    lines.append("cm_rgob_coverage = {")
    lines.append("\tvalue = 0")
    keyword = "if"
    for building in options_by_building:
        lines.append(f"\t{keyword} = {{")
        lines.append(f"\t\tlimit = {{ building_type = building_type:{building} }}")
        lines.append(f"\t\tlocation = {{ province = {{ add = cm_rgob_b_{building} }} }}")
        lines.append("\t}")
        keyword = "else_if"
    lines.append("}")
    lines.append("")

    lines.append(
        "# Location scope. Same coverage keyed by the build-location list's viewed\n"
        "# building type (cm_rgob_selected_idx on the viewer, stored by\n"
        "# cm_rgob_store_selected_type from the cm_rgob_type_index map).")
    lines.append("cm_rgob_coverage_selected = {")
    lines.append("\tvalue = 0")
    lines.append("\tif = {")
    lines.append("\t\tlimit = { scope:target = { has_variable = cm_rgob_selected_idx } }")
    keyword = "if"
    for k, building in enumerate(options_by_building, start=1):
        lines.append(f"\t\t{keyword} = {{")
        lines.append(f"\t\t\tlimit = {{ scope:target = {{ var:cm_rgob_selected_idx = {k} }} }}")
        lines.append(f"\t\t\tprovince = {{ add = cm_rgob_b_{building} }}")
        lines.append("\t\t}")
        keyword = "else_if"
    lines.append("\t}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_effects(options_by_building):
    lines = [GENERATED_HEADER]
    lines.append(
        "# Seeds the building_type -> dispatch index map cm_rgob_store_selected_type\n"
        "# resolves cm_rgob_selected_idx from. Called from cm_on_init_lobby_globals.")
    lines.append("cm_rgob_seed_type_index = {")
    lines.append("\tclear_global_variable_map = cm_rgob_type_index")
    for k, building in enumerate(options_by_building, start=1):
        lines.append("\tadd_to_global_variable_map = { name = cm_rgob_type_index "
                     f"key = building_type:{building} value = {k} }}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(
        description="Generate the R.G.O. Bonus building filter script values "
                    "from vanilla building production methods and goods.")
    parser.add_argument(
        "--game-dir", type=str, default=None,
        help="Path to EU5 game directory (overrides config.toml).")
    args = parser.parse_args()

    game_dir = resolve_game_dir(args.game_dir)
    goods_categories = parse_goods(os.path.join(game_dir, GOODS_SUBDIR))
    if not goods_categories:
        raise SystemExit("No goods parsed")

    external_pms = parse_production_methods(game_dir, goods_categories)
    buildings, dangling = parse_buildings(
        game_dir, goods_categories, external_pms)
    if not buildings:
        raise SystemExit("No buildings with production methods parsed")
    options_by_building = collect_building_options(buildings, goods_categories)
    if not options_by_building:
        raise SystemExit("No buildings with raw-material-consuming production methods")

    write_output(OUT_SCRIPT_VALUES, emit_script_values(options_by_building))
    write_output(OUT_EFFECTS, emit_effects(options_by_building))

    total_options = sum(len(d["options"]) for d in options_by_building.values())
    for path in (OUT_SCRIPT_VALUES, OUT_EFFECTS):
        print(f"Wrote {os.path.relpath(path, ROOT_DIR).replace(os.sep, '/')}")
    print(f"  {len(options_by_building)} building types, {total_options} options")
    if dangling:
        rel_pm = PRODUCTION_METHODS_SUBDIR.replace(os.sep, "/")
        print("  WARNING: possible_production_methods entries with no definition "
              f"in {rel_pm}, skipped: {', '.join(sorted(dangling))}")


if __name__ == "__main__":
    main()
