#!/usr/bin/env python3
"""Generate the vanilla-derived values for the placement finder map modes.

The governor/capital placement finder (cm_governor_finder, cm_capital_finder)
mirrors a few vanilla numbers in its cost model that shift between game patches.
This tool reads them from vanilla and emits:

  in_game/common/script_values/cm_proximity_finder_generated_values.txt

containing:

  - cm_pf_road_reduction_value: the land-cost reduction from the best unlocked
    road, read from road_types (each type's `proximity` field) and advances
    (which advance unlocks each road). A road cuts the land cost by a flat base
    (GRAVEL_ROAD_REDUCTION, verified in game, not a vanilla field) plus that
    type's proximity field.
  - cm_pf_cap_adj_value / cm_pf_capb_extra_value: the capital-in-topography
    terrain deltas, read from topography (each topography's `proximity` field)
    and static_modifiers/capital_in_topography.txt (the per-topography
    `<topo>_proximity_impact` a capital grants). A capital in a topography
    shifts that topography's terrain penalty by proximity * impact.

The rest of the finder (cost formulas, the search itself, the tooltip readers)
is hand-authored in cm_proximity_finder_script_values.txt and
cm_proximity_finder_effects.txt and reuses cm_location_proximity_modifier for
the base terrain penalty, so this tool only emits the values above.

Usage:
    python tools/cm_generate_proximity_finder.py [--game-dir PATH]

The game directory comes from `game_directory` in tools/config.toml, or is
auto-detected from the common Steam install paths when that is blank.
"""

import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
CONFIG_PATH = os.path.join(SCRIPT_DIR, "config.toml")

STEAM_GAME_PATHS = [
    os.path.join("C:" + os.sep, "Steam", "steamapps", "common",
                 "Europa Universalis V", "game"),
    os.path.join("C:" + os.sep, "Program Files (x86)", "Steam", "steamapps",
                 "common", "Europa Universalis V", "game"),
    os.path.join("C:" + os.sep, "Program Files", "Steam", "steamapps",
                 "common", "Europa Universalis V", "game"),
]

ROAD_TYPES_SUBDIR = os.path.join("in_game", "common", "road_types")
ADVANCES_SUBDIR = os.path.join("in_game", "common", "advances")
TOPOGRAPHY_SUBDIR = os.path.join("in_game", "common", "topography")
CAPITAL_IN_TOPOGRAPHY = os.path.join(
    "main_menu", "common", "static_modifiers", "capital_in_topography.txt")

OUT_PATH = os.path.join(
    ROOT_DIR, "in_game", "common", "script_values",
    "cm_proximity_finder_generated_values.txt")

# A road cuts the land distance cost by this flat base plus the road type's
# proximity field. The base is verified in game; road_cost_on_distance_from_capital
# is a dead modifier the engine never uses, so the base has no vanilla field to read.
GRAVEL_ROAD_REDUCTION = 20

GENERATED_HEADER = (
    "# Generated by tools/cm_generate_proximity_finder.py - do not edit by hand.\n"
    "# Regenerate after a game update.\n"
)

ASSIGN_BLOCK = re.compile(r"([A-Za-z0-9_.]+)\s*=\s*\{")
ASSIGN_SCALAR = re.compile(r"([A-Za-z0-9_.]+)\s*=\s*(-?[A-Za-z0-9_.:]+)")


def _load_config():
    if tomllib is None:
        return {}
    try:
        with open(CONFIG_PATH, "rb") as f:
            return tomllib.load(f)
    except FileNotFoundError:
        return {}


def resolve_game_dir(cli_game_dir):
    if cli_game_dir:
        if os.path.isdir(cli_game_dir):
            return cli_game_dir
        sys.exit(f"Game directory not found: {cli_game_dir}")

    configured = _load_config().get("game_directory", "")
    if configured and os.path.isdir(configured):
        return configured

    for path in STEAM_GAME_PATHS:
        if os.path.isdir(path):
            return path

    sys.exit("Could not locate EU5 game directory. "
             "Set 'game_directory' in tools/config.toml or pass --game-dir.")


def strip_comments(text):
    return "\n".join(line.split("#", 1)[0] for line in text.split("\n"))


def find_matching_brace(text, open_idx):
    depth = 0
    for i in range(open_idx, len(text)):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError(f"unbalanced braces from offset {open_idx}")


def child_blocks(text):
    """Yield (name, inner_text) for each `name = { ... }` in `text`."""
    pos = 0
    while True:
        match = ASSIGN_BLOCK.search(text, pos)
        if not match:
            return
        open_idx = match.end() - 1
        close_idx = find_matching_brace(text, open_idx)
        yield match.group(1), text[open_idx + 1:close_idx]
        pos = close_idx + 1


def remove_child_blocks(text):
    out = []
    pos = 0
    while True:
        match = ASSIGN_BLOCK.search(text, pos)
        if not match:
            out.append(text[pos:])
            return "".join(out)
        close_idx = find_matching_brace(text, match.end() - 1)
        out.append(text[pos:match.start()])
        pos = close_idx + 1


def scalar_assignments(text):
    """Yield (key, value) for `key = value` lines outside child blocks."""
    for match in ASSIGN_SCALAR.finditer(remove_child_blocks(text)):
        yield match.group(1), match.group(2)


def read_pdx(path):
    with open(path, "r", encoding="utf-8-sig") as f:
        return strip_comments(f.read())


def iter_db_files(directory):
    for name in sorted(os.listdir(directory)):
        if name.endswith(".txt") and name not in ("readme.txt", "__readme.txt"):
            yield os.path.join(directory, name)


def fmt_num(value):
    """Format a number the way the vanilla script files do: no trailing zeros."""
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text if text else "0"


def parse_road_reductions(game_dir):
    """road type -> (level, proximity), highest level first."""
    roads = {}
    road_dir = os.path.join(game_dir, ROAD_TYPES_SUBDIR)
    for path in iter_db_files(road_dir):
        for name, body in child_blocks(read_pdx(path)):
            fields = dict(scalar_assignments(body))
            level = int(float(fields.get("level", 0)))
            proximity = float(fields.get("proximity", 0))
            roads[name] = (level, proximity)

    unlocks = {}
    adv_dir = os.path.join(game_dir, ADVANCES_SUBDIR)
    for path in iter_db_files(adv_dir):
        for name, body in child_blocks(read_pdx(path)):
            road = dict(scalar_assignments(body)).get("unlock_road_type")
            if road:
                unlocks[road] = name

    rows = []
    for road, (level, proximity) in roads.items():
        advance = unlocks.get(road)
        if advance is None:
            continue
        rows.append((level, road, advance, GRAVEL_ROAD_REDUCTION + proximity))
    rows.sort(reverse=True)
    if not rows:
        sys.exit("No road types with an unlocking advance were found.")
    return rows


def parse_capital_topography(game_dir):
    """(topography, proximity, impact_magnitude), by topography file order."""
    proximities = []
    topo_dir = os.path.join(game_dir, TOPOGRAPHY_SUBDIR)
    for path in iter_db_files(topo_dir):
        for name, body in child_blocks(read_pdx(path)):
            proximity = float(dict(scalar_assignments(body)).get("proximity", 0))
            if proximity != 0:
                proximities.append((name, proximity))

    impacts = {}
    text = read_pdx(os.path.join(game_dir, CAPITAL_IN_TOPOGRAPHY))
    for name, body in child_blocks(text):
        if not name.startswith("capital_in_"):
            continue
        topo = name[len("capital_in_"):]
        value = dict(scalar_assignments(body)).get(f"{topo}_proximity_impact")
        if value is not None:
            impacts[topo] = abs(float(value))

    rows = []
    for topo, proximity in proximities:
        if topo in impacts:
            rows.append((topo, proximity, impacts[topo]))
    if not rows:
        sys.exit("No topography with a capital proximity impact was found.")
    return rows


def build_output(road_rows, topo_rows):
    lines = [GENERATED_HEADER]

    lines.append(
        "# Country scope. Land-cost reduction from the best unlocked road, the best\n"
        f"# roads assumed built everywhere: {GRAVEL_ROAD_REDUCTION} (verified in game; the\n"
        "# road_cost_on_distance_from_capital modifier is unused) plus the road type's\n"
        "# proximity field.")
    lines.append("cm_pf_road_reduction_value = {")
    lines.append("\tvalue = 0")
    for idx, (level, road, advance, reduction) in enumerate(road_rows):
        keyword = "if" if idx == 0 else "else_if"
        bonus = reduction - GRAVEL_ROAD_REDUCTION
        note = (f"# {GRAVEL_ROAD_REDUCTION} + {road} proximity {fmt_num(bonus)}"
                if bonus else f"# {GRAVEL_ROAD_REDUCTION}, {road} has no proximity field")
        lines.append(f"\t{keyword} = {{")
        lines.append(f"\t\tlimit = {{ has_advance = {advance} }}")
        lines.append(f"\t\tadd = {fmt_num(reduction)} {note}")
        lines.append("\t}")
    lines.append("}")
    lines.append("")

    lines.append(
        "# Location scope. Expects scope:cm_pf_capital (the country's capital), when it\n"
        "# exists. Terrain-impact adjustment for a capital candidate: a location sharing\n"
        "# the current capital's topography loses the capital-in-topography benefit it\n"
        "# currently enjoys (proximity times the impact the capital grants).")
    lines.append("cm_pf_cap_adj_value = {")
    lines.append("\tvalue = 0")
    for idx, (topo, proximity, impact) in enumerate(topo_rows):
        keyword = "if" if idx == 0 else "else_if"
        delta = proximity * impact
        lines.append(f"\t{keyword} = {{")
        lines.append("\t\tlimit = {")
        lines.append("\t\t\texists = scope:cm_pf_capital")
        lines.append(f"\t\t\ttopography = {topo}")
        lines.append(f"\t\t\tscope:cm_pf_capital = {{ topography = {topo} }}")
        lines.append("\t\t}")
        lines.append(f"\t\tadd = {fmt_num(delta)} "
                     f"# {topo} proximity {fmt_num(proximity)} times the "
                     f"{fmt_num(impact)} capital-in-topography impact.")
        lines.append("\t}")
    lines.append("}")
    lines.append("")

    lines.append(
        "# Location scope. Terrain-impact gain when the candidate capital shares this\n"
        "# location's topography (the mirror of cm_pf_cap_adj_value for the new capital).")
    lines.append("cm_pf_capb_extra_value = {")
    lines.append("\tvalue = 0")
    for idx, (topo, proximity, impact) in enumerate(topo_rows):
        keyword = "if" if idx == 0 else "else_if"
        delta = -(proximity * impact)
        lines.append(f"\t{keyword} = {{")
        lines.append(f"\t\tlimit = {{ topography = {topo} }}")
        lines.append(f"\t\tadd = {fmt_num(delta)}")
        lines.append("\t}")
    lines.append("}")

    return "\n".join(lines) + "\n"


def write_output(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    with open(path, "wb") as f:
        f.write(b"\xef\xbb\xbf" + normalized.encode("utf-8"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-dir", dest="game_dir", default=None)
    args = parser.parse_args()

    game_dir = resolve_game_dir(args.game_dir)
    road_rows = parse_road_reductions(game_dir)
    topo_rows = parse_capital_topography(game_dir)
    write_output(OUT_PATH, build_output(road_rows, topo_rows))
    rel = os.path.relpath(OUT_PATH, ROOT_DIR).replace(os.sep, "/")
    print(f"Wrote {rel} "
          f"({len(road_rows)} road tiers, {len(topo_rows)} topographies).")


if __name__ == "__main__":
    main()
