#!/usr/bin/env python3
"""Generate the auto-town-rights location-eligibility trigger from vanilla data.

Reads every vanilla `town_rights_type` definition and copies its `allow` block
verbatim into a single scripted trigger, keyed by town right. The auto-grant loop
calls that trigger so it only grants a right on a location the engine would allow.

The `allow` body is copied without rewriting: the loop saves the candidate
location as scope:target and the right as scope:town_right, which are exactly the
scopes vanilla `allow` blocks read. New triggers Paradox adds to an `allow` block
therefore pass straight through on the next regeneration.

Usage:
    python tools/cm_generate_town_rights_allow.py [--game-dir PATH]

The game directory comes from `game_directory` in tools/config.toml, or is
auto-detected from the common Steam install paths when that is blank.
"""

import argparse
import os
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    try:
        import tomli as tomllib
    except ModuleNotFoundError:
        tomllib = None

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
CONFIG_PATH = os.path.join(SCRIPT_DIR, "config.toml")

STEAM_GAME_PATHS = [
    os.path.join("C:" + os.sep, "Steam", "steamapps", "common",
                 "Europa Universalis V", "game"),
    os.path.join("C:" + os.sep, "Program Files (x86)", "Steam", "steamapps",
                 "common", "Europa Universalis V", "game"),
    os.path.join("C:" + os.sep, "Program Files", "Steam", "steamapps",
                 "common", "Europa Universalis V", "game"),
]

TOWN_RIGHTS_SUBDIR = os.path.join("in_game", "common", "town_rights")

OUTPUT_PATH = os.path.join(
    ROOT_DIR, "in_game", "common", "scripted_triggers",
    "cm_auto_town_rights_allow_triggers.txt")

TRIGGER_NAME = "cm_can_grant_specific_town_right_at_location"

ASSIGN_BLOCK = re.compile(r"([A-Za-z_][A-Za-z0-9_.:]*)\s*=\s*\{")

HEADER = (
    "# Generated by tools/cm_generate_town_rights_allow.py - do not edit by hand.\n"
    "# Regenerate after a game update.\n"
    "#\n"
    "# Country trigger. Mirrors each vanilla town_rights_type `allow` block so auto-grant\n"
    "# only grants a right on a location the engine would allow it on.\n"
    "# Expects scope:town_right (the right) and scope:target (the candidate location).\n"
    "# Rights with no `allow` restriction fall through to the trailing trigger_else.\n"
)


def _load_config():
    if tomllib is None:
        return {}
    try:
        with open(CONFIG_PATH, "rb") as f:
            return tomllib.load(f)
    except FileNotFoundError:
        return {}


def resolve_game_dir(cli_game_dir):
    if cli_game_dir:
        if os.path.isdir(cli_game_dir):
            return cli_game_dir
        sys.exit(f"Game directory not found: {cli_game_dir}")

    configured = _load_config().get("game_directory", "")
    if configured and os.path.isdir(configured):
        return configured

    for path in STEAM_GAME_PATHS:
        if os.path.isdir(path):
            return path

    sys.exit("Could not locate EU5 game directory. "
             "Set 'game_directory' in tools/config.toml or pass --game-dir.")


def strip_comments(text):
    """Drop `#` comments while preserving line structure for brace matching."""
    return "\n".join(line.split("#", 1)[0] for line in text.split("\n"))


def find_matching_brace(text, open_idx):
    depth = 0
    in_str = False
    for i in range(open_idx, len(text)):
        ch = text[i]
        if in_str:
            if ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError(f"unbalanced braces from offset {open_idx}")


def child_blocks(text):
    """Yield (name, inner_text) for each `name = { ... }` directly inside `text`."""
    pos = 0
    while True:
        match = ASSIGN_BLOCK.search(text, pos)
        if not match:
            return
        open_idx = match.end() - 1
        close_idx = find_matching_brace(text, open_idx)
        yield match.group(1), text[open_idx + 1:close_idx]
        pos = close_idx + 1


def reindent(body, base="\t\t"):
    lines = body.split("\n")
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    if not lines:
        return ""
    common = min(len(ln) - len(ln.lstrip("\t ")) for ln in lines if ln.strip())
    return "\n".join((base + ln[common:]).rstrip() if ln.strip() else ""
                     for ln in lines)


def collect_allow_blocks(town_rights_dir):
    rights = []
    for name in sorted(os.listdir(town_rights_dir)):
        if not name.endswith(".txt") or name == "readme.txt":
            continue
        path = os.path.join(town_rights_dir, name)
        with open(path, "r", encoding="utf-8-sig") as f:
            text = strip_comments(f.read())
        for right_name, body in child_blocks(text):
            allow = next((inner for child, inner in child_blocks(body)
                          if child == "allow"), None)
            if allow is None:
                continue
            indented = reindent(allow)
            if indented:
                rights.append((right_name, indented))
    return rights


def render(rights):
    branches = []
    for idx, (name, body) in enumerate(rights):
        keyword = "trigger_if" if idx == 0 else "trigger_else_if"
        branches.append(
            f"\t{keyword} = {{\n"
            f"\t\tlimit = {{ scope:town_right = town_rights_type:{name} }}\n"
            f"{body}\n"
            f"\t}}"
        )
    branches.append("\ttrigger_else = {\n\t\talways = yes\n\t}")
    return f"{HEADER}{TRIGGER_NAME} = {{\n" + "\n".join(branches) + "\n}\n"


def write_output(text):
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    data = b"\xef\xbb\xbf" + normalized.replace("\n", "\r\n").encode("utf-8")
    with open(OUTPUT_PATH, "wb") as f:
        f.write(data)


def main():
    parser = argparse.ArgumentParser(
        description="Generate the auto-town-rights location-eligibility "
                    "trigger from vanilla town_rights allow blocks.")
    parser.add_argument(
        "--game-dir", type=str, default=None,
        help="Path to EU5 game directory (overrides config.toml).")
    args = parser.parse_args()

    town_rights_dir = os.path.join(resolve_game_dir(args.game_dir),
                                   TOWN_RIGHTS_SUBDIR)
    if not os.path.isdir(town_rights_dir):
        sys.exit(f"town_rights directory not found: {town_rights_dir}")

    rights = collect_allow_blocks(town_rights_dir)
    if not rights:
        sys.exit(f"No town rights with allow blocks found in {town_rights_dir}")

    write_output(render(rights))
    rel = os.path.relpath(OUTPUT_PATH, ROOT_DIR).replace(os.sep, "/")
    print(f"Wrote {len(rights)} allow branches to {rel}")
    for name, _ in rights:
        print(f"  {name}")


if __name__ == "__main__":
    main()
