#!/usr/bin/env ruby
# frozen_string_literal: true

require "pathname"

GAME_ROOT_DEFAULT = Pathname.new("/Volumes/Europa Universalis V/game")
REPO_ROOT_DEFAULT = Pathname.new(__dir__).parent
OUTPUT_PATH_DEFAULT = REPO_ROOT_DEFAULT.join("in_game/common/scripted_triggers/lsq_can_afford_building.txt")

IDENTIFIER_RE = /[A-Za-z0-9_:\.\-]+/
NUMERIC_RE = /\A-?\d+(?:\.\d+)?\z/

def read_text(path)
  File.read(path, encoding: "bom|utf-8")
rescue Errno::ENOENT
  warn "Missing file: #{path}"
  ""
end

def strip_comments(line)
  line.sub(/#.*/, "")
end

def parse_top_level_blocks(text)
  sanitized = text.each_line.map { |line| strip_comments(line) }.join
  blocks = {}
  i = 0
  n = sanitized.length

  while i < n
    if (match = /\G\s*(#{IDENTIFIER_RE.source})\s*=\s*\{/m.match(sanitized, i))
      block_id = match[1]
      brace_index = match.end(0) - 1
      depth = 1
      j = brace_index + 1

      while j < n && depth.positive?
        ch = sanitized[j]
        depth += 1 if ch == "{"
        depth -= 1 if ch == "}"
        j += 1
      end

      if depth.zero?
        blocks[block_id] = sanitized[(brace_index + 1)...(j - 1)]
        i = j
        next
      end

      warn "Unclosed block for '#{block_id}'"
      break
    end

    i += 1
  end

  blocks
end

def parse_root_assignments(block_text)
  assignments = {}
  depth = 0

  block_text.each_line do |raw_line|
    line = strip_comments(raw_line).strip
    next if line.empty?

    if depth.zero? && (m = /\A(#{IDENTIFIER_RE.source})\s*=\s*([^\{\}\r\n]+?)\s*\z/.match(line))
      assignments[m[1]] = m[2].strip
    end

    depth += line.count("{")
    depth -= line.count("}")
  end

  assignments
end

def parse_building_type_profiles(game_root)
  result = {}
  dir = game_root.join("in_game/common/building_types")

  Dir.glob(dir.join("*.txt").to_s).sort.each do |path|
    blocks = parse_top_level_blocks(read_text(path))
    blocks.each do |building_type, body|
      attrs = parse_root_assignments(body)
      result[building_type] = attrs["construction_demand"]
    end
  end

  result
end

def parse_demand_profiles(game_root)
  result = {}
  demand_paths = [
    game_root.join("in_game/common/goods_demand/building_construction_costs.txt"),
    game_root.join("in_game/common/goods_demand/special_construction_demands.txt")
  ]

  demand_paths.each do |path|
    blocks = parse_top_level_blocks(read_text(path))
    blocks.each do |profile_id, body|
      attrs = parse_root_assignments(body)
      next unless attrs["category"] == "building_construction"

      goods = {}
      attrs.each do |key, value|
        next if key == "category"
        goods[key] = value if NUMERIC_RE.match?(value)
      end

      result[profile_id] = goods
    end
  end

  result
end

def build_trigger_text(building_type, goods)
  lines = []
  lines << "# Root is the location"
  lines << "lsq_can_afford_#{building_type} = {"
  lines << "\tAND = {"

  if goods.empty?
    lines << "\t\talways = yes"
  else
    goods.sort_by { |good, _| good }.each do |good, amount|
      lines << "\t\tgoods:#{good} = { save_temporary_scope_as = good }"
      lines << "\t\tlsq_get_max_required_construction_demand_to_still_allow_building >= #{amount}"
    end
  end

  lines << "\t}"
  lines << "}"
  lines.join("\n")
end

def build_switch_trigger_text(building_ids)
  lines = []
  lines << "# Root is the building type, also expects scope:location"
  lines << "lsq_can_afford_switch_based_on_building_type = {"

  if building_ids.empty?
    lines << "\talways = no"
  else
    building_ids.each_with_index do |building_type, index|
      branch = index.zero? ? "trigger_if" : "trigger_else_if"
      lines << "\t#{branch} = { limit = { $target$ = building_type:#{building_type} }"
      lines << "\t\tlsq_can_afford_#{building_type} = yes"
      lines << "\t}"
    end
    lines << "\ttrigger_else = {"
    lines << "\t\talways = no"
    lines << "\t}"
  end

  lines << "}"
  lines.join("\n")
end

def generate_file(game_root:, output_path:)
  building_to_profile = parse_building_type_profiles(game_root)
  profile_to_goods = parse_demand_profiles(game_root)

  default_profile = "default_construct_building"
  unless profile_to_goods.key?(default_profile)
    warn "Missing required fallback profile '#{default_profile}' in goods demand files."
  end

  building_ids = building_to_profile.keys.sort
  sections = []

  sections << "# AUTO-GENERATED FILE. DO NOT EDIT BY HAND."
  sections << "# Generated by tools/generate_lsq_can_afford_building_triggers.rb"
  sections << "# Sources:"
  sections << "# - #{game_root.join('in_game/common/building_types/*.txt')}"
  sections << "# - #{game_root.join('in_game/common/goods_demand/building_construction_costs.txt')}"
  sections << "# - #{game_root.join('in_game/common/goods_demand/special_construction_demands.txt')}"
  sections << ""
  sections << build_switch_trigger_text(building_ids)
  sections << ""

  building_ids.each do |building_type|
    profile = building_to_profile[building_type] || default_profile
    warn "Building '#{building_type}' has no construction_demand, using '#{default_profile}'." unless building_to_profile[building_type]
    goods = profile_to_goods[profile]
    if goods.nil?
      warn "Building '#{building_type}' references missing profile '#{profile}', falling back to '#{default_profile}'."
      goods = profile_to_goods[default_profile] || {}
    end
    warn "Building '#{building_type}' resolved to empty goods map." if goods.empty?
    sections << build_trigger_text(building_type, goods)
    sections << ""
  end

  output_path.dirname.mkpath unless output_path.dirname.directory?
  File.write(output_path, sections.join("\n"))
  puts "Generated #{output_path} (#{building_ids.size + 1} triggers, including switch trigger)"
end

game_root = ARGV[0] ? Pathname.new(ARGV[0]) : GAME_ROOT_DEFAULT
output_path = ARGV[1] ? Pathname.new(ARGV[1]) : OUTPUT_PATH_DEFAULT

generate_file(game_root: game_root, output_path: output_path)
